#fortnite.py
#the game fortnite
# by Macauley Tosi

def main():
    print("welcome to Fortnite Battle royal!")
    print("The last one to survive gets the victory royal!")
    username = input("whats your username you would like? ")
    print(username,"has entered the Battle bus, and you decide where to land")
    location = input("whats the name of the location you land? ")
    print(username,"has thanked the bus driver")
    print("You open your parachute and")
    print("you land at", location,"and open a large glowing chest")
    print("a assortment of weapons bust out of the chest in front of you") 
    print("Then a rain of bullets start flying in your direction!")
    weapon = input("QUICK! what weapon do you pick up?! ")
    print("Nice, I would've picked the", weapon,"too.")
    print("the stucture your in falls down, you need to build protection!")
    stucture =input("what do you build to protect yourself? ")
    print("you build a", stucture,"that should hold them off")
    print("you climb to the top of your", stucture,"and the enemy is in your sight")
    input("Quick! hit any key and enter to eliminate them!")
    print("you give your enemy a few hit markers, until you finally eliminate them!")
    print(username,"eliminated User[203] with the", weapon,)
    print("VICTORY DANCE")
    print("but the battle isn't over...")
    kills = input("whats the estimation of eliminations you have in total? ")
    print("WOW", kills,"Kills? Thats epic!")
    print("get out there into battle! The victory royal is waiting!")
    print("as the others slowly die off, there is one more opponent waiting for you.")
    print("The last opponent is in your", weapon,"'s ironsight")
    input("Hit any key and enter to eliminate him!!")
    print("VICTORY ROYAL!! DANCE TIME!!")
    print(username,"has eliminated User[935] with the", weapon)
    print("With", kills,"kills(+1) you won the game!")
    print("GG")
    print("Thank you for playing =)")
    input("press <Enter> to exit the game")
main()  
    
